version: "3.8"

services:

  activemq:
    image: webcenter/activemq:latest
    container_name: betterjavacode_activemq
    restart: on-failure
    networks:
      - bjc-net
    ports:
      - 8161:8161
      - 61616:61616
    environment:
      #ACTIVEMQ_ADMIN_LOGIN: admin
      #ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048

  messagesender:
    build:
      context: ./messagesender
      dockerfile: Dockerfile
    depends_on:
      - activemq
    ports:
      - 8080:8080
    networks:
      - bjc-net
    environment:
      ACTIVE_MQ_BROKER_URL: tcp://activemq:61616

  messagereceiver:
    build:
      context: ./messagereceiver
      dockerfile: Dockerfile
    depends_on:
      - activemq
      - messagesender
    ports:
      - 8081:8081
    networks:
      - bjc-net
    environment:
      ACTIVE_MQ_BROKER_URL: tcp://activemq:61616

networks:
  bjc-net:
    driver: bridge
